branches:
  - master
  - 1.x
  - 2.x
  # This is very useful when debugging drone related issues. Just prefix your branch with "drone-"
  # to trigger a drone build.
  - drone-*

workspace:
  base: /root/go
  path: src/github.com/presslabs/mysql-operator

clone:
  git:
    image: plugins/git
    depth: 100
    tags: true

pipeline:
  dependencies:
    image: quay.io/presslabs/bfc
    commands:
      - make dependencies

  lint:
    group: lint
    image: quay.io/presslabs/bfc:0.1
    commands:
      - make lint

  lint-chart:
    group: lint
    image: quay.io/presslabs/kluster-toolbox
    pull: true
    commands:
      - helm lint hack/charts/mysql-operator
      - helm dep build hack/charts/mysql-operator

  test:
    group: test
    image: quay.io/presslabs/bfc
    commands:
      - make test

  verify-generate:
    image: quay.io/presslabs/bfc:0.1
    commands:
      - make -s fmt generate manifests
      - git diff --exit-code

  build-chart:
    group: build
    image: quay.io/presslabs/bfc
    commands:
      - make chart

  publish-operator:
    group: publish
    image: plugins/docker
    repo: shao0222/mysql-operator
    tags: ["${DRONE_BRANCH/master/latest}"]
    secrets:
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
    when:
      event: push

  publish-operator:
    group: publish
    image: plugins/docker
    repo: shao0222/mysql-operator
    auto_tag: true
    secrets:
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
    when:
      event: tag

  publish-sidecar:
    group: publish
    image: plugins/docker
    repo: shao0222/mysql-operator-sidecar
    dockerfile: Dockerfile.sidecar
    tags: ["${DRONE_BRANCH/master/latest}"]
    secrets:
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
    when:
      event: push

  publish-sidecar:
    group: publish
    image: plugins/docker
    repo: shao0222/mysql-operator-sidecar
    dockerfile: Dockerfile.sidecar
    auto_tag: true
    secrets:
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
    when:
      event: tag

  publish-orchestrator:
    group: publish
    image: plugins/docker
    repo: shao0222/mysql-operator-orchestrator
    dockerfile: Dockerfile.orchestrator
    tags: ["${DRONE_BRANCH/master/latest}"]
    secrets:
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
    when:
      event: push

  publish-orchestrator:
    group: publish
    image: plugins/docker
    repo: shao0222/mysql-operator-orchestrator
    dockerfile: Dockerfile.orchestrator
    auto_tag: true
    secrets:
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
    when:
      event: tag